### ISSUE TITLE
Validation does not work for Coral UI 3 dialogs

### ISSUE THREAD

**Issue by ThomasLeidecker** [namics/aem-authoring-extensions#5]
The validation of dialog fields does not work for Coral UI 3 dialog elements.
- Coral UI 2 works:               granite/ui/components/foundation/form/textfield
- Coral UI 3 does not work: granite/ui/components/coral/foundation/form/textfield

```
<text 
    jcr:primaryType="nt:unstructured"
    sling:resourceType="granite/ui/components/coral/foundation/form/textfield"
    fieldLabel="Text"
    name="./text"
    regex="^(\\w)+$"
    regex-errormsg="Only word characters are allowed (a-z, A-Z, 0-9, _)." />
```

**Comment by mkiti** [comment]
Hi Thomas,

for UI 3 you have to use the granite:class attribute to add "data" attributes to the Elements (https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/docs/server/commonattrs.html). Can you please recheck if you change your dialog to:

<text 
    jcr:primaryType="nt:unstructured"
    sling:resourceType="granite/ui/components/coral/foundation/form/textfield"
    fieldLabel="Text"
    name="./text">
<granite:data
                                jcr:primaryType="nt:unstructured"
                                regex="^(\\w)+$"
                                regex-errormsg="Only word characters are allowed (a-z, A-Z, 0-9, _)."/>
</text>

**Comment by ThomasLeidecker** [comment]
Thanks. Works.
Please update the documentation: https://github.com/namics/aem-authoring-extensions/blob/6.5/master/README.md

**Comment by mkiti** [comment]
> Thanks. Works. :-)
> Could you please update the documentation: https://github.com/namics/aem-authoring-extensions/blob/6.5/master/README.md

Readme will be update with following pull request.
https://github.com/namics/aem-authoring-extensions/pull/6

It contains also some changes to improve support for coral ui 3 regarding the field dependency feature.
